Deletion - model and crud
resource-watch/authorization pull request #36
Opened 2022-06-29 15:36 UTC by tiagojsag

2022-06-30 15:22 UTC, gtempus commented on src/providers/okta.provider.ts
> +            await DeletionService.createDeletion(newDeletionData);
I saw this mentioned in [your JIRA comments](https://gfw.atlassian.net/browse/GTC-1881?focusedCommentId=13242). Good call. 💪

2022-06-30 15:40 UTC, gtempus commented on src/providers/okta.provider.ts
> +
I see pagination param parsing happening in a few locations in this PR (I appreciate the `parseInt` refactor). What are your thoughts on DRYing this up?

2022-06-30 17:19 UTC, solomon-negusse requested changes

2022-06-30 17:19 UTC, solomon-negusse commented on src/providers/okta.provider.ts
> +            pageNumber = ctx.query.page && number ? parseInt(number, 10) : 1;
is the check for `ctx.query.page` needed here with the `if` logic already checking for that?
is there a way to modify this block so we're not specifying default `pageNumber` and `limit` in a couple of places?

2022-06-30 17:19 UTC, solomon-negusse commented on src/routes/deletion.router.ts
> +                size: Joi.number().integer().min(1).max(250).default(10),
should we make page parameters constants since they are used in multiple places? also curious of what constraints you're considering for max size and if that's something that's varying across resource types.

2022-06-30 17:19 UTC, solomon-negusse commented on src/routes/deletion.router.ts
> +            limit = ctx.query.page && size ? parseInt(size, 10) : 10;
please see the comments in `providers/okta.provider.ts`

2022-06-30 17:19 UTC, solomon-negusse commented on src/routes/deletion.router.ts
> +            if (limit > 100) {
Will this still be needed with the JOI validator specifying  max size? If we have to keep it, the max size is set to 250 in the validator. Re: comment on using constants.

2022-07-01 08:33 UTC, tiagojsag commented
@solomon-negusse @gtempus thank you both for the feedback. I have removed the duplicated/redundant code you pointed out, plus a few more duplicated functions I came across along the way. 

I am leaving the max page size as a hardcoded value, instead of a constant, because a) it's only used once, and b) it's a RW API-wide standard that is documented and applied everywhere (except where it's not, for legacy + BC reasons), so odds that it will change anytime soon are realistically 0.

Let me know if I forgot to address anyting

2022-07-01 14:21 UTC, solomon-negusse commented on src/utils.ts
> +            page = number ? parseInt(number, 10) : 1;
Minor but  `if (number) page = parseInt(number, 10)` would avoid having to re-define defaults defined above.

2022-07-01 14:22 UTC, solomon-negusse approved these changes

2022-07-01 15:17 UTC, merged